### ISSUE TITLE
Fix DNS resolution through VPN

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#103]
In #257 we added support for Wireguard VPN, though it seems like DNS resolution through the VPN is not working properly.
This is quite important to make this a useful way for people to interact with the system, so we should get it running.

**Comment by sshi100** [comment]
Requirements (per @bmonkman )
- Able to resolve VPC dns (like RDS domain) to internal IPs

**Comment by sshi100** [comment]
Solutions:
option 1: use k8s kube-dns as DNS server
option 2: use wireguard pod as DNS server, implement dnsmasql server inside
option 3: use an independent DNS server in EC2

In client side, add corresponding IP into client resolver configuration (like /etc/resolv.conf)

**Comment by sshi100** [comment]
per discussion with @bmonkman , we prefer  **option 1.a** if it covers both k8s and vpc.

**Comment by sshi100** [comment]
Per test, all confirmed, as long as I set DNS = 172.20.0.10 into WireGurard client configuration, all worked.

for confirmation:
- DNS level,  note: for MacOS, use its dns tool dscacheutil (rather than nslookup/dig which are not working with macOS mDNS resolver)

> $ dscacheutil -q host -a name ip-10-10-81-4.us-west-2.compute.internal

name: ip-10-10-81-4.us-west-2.compute.internal
ip_address: 10.10.81.4
$ dscacheutil -q host -a name database.piggycloud2-me.svc.cluster.local
name: piggycloud2-me-stage.cmz3djbw9edx.us-west-2.rds.amazonaws.com
alias: database.piggycloud2-me.svc.cluster.local
ip_address: 10.10.10.183
$ dscacheutil -q host -a name piggycloud2-me-stage.cmz3djbw9edx.us-west-2.rds.amazonaws.com
name: piggycloud2-me-stage.cmz3djbw9edx.us-west-2.rds.amazonaws.com
ip_address: 10.10.10.183





10:36
TCP/IP level
$ telnet database.piggycloud2-me.svc.cluster.local 3306
Trying 10.10.10.183...
Connected to piggycloud2-me-stage.cmz3djbw9edx.us-west-2.rds.amazonaws.com.
Escape character is '^]'.
J
5.7.26Z&+%CyXZ/su=B{R_6%mysql_native_password^C
^C
Connection closed by foreign host.

**Comment by sshi100** [comment]
PR: https://github.com/commitdev/zero-aws-eks-stack/pull/111

**Comment by sshi100** [comment]
Completed
